"""Emit LaTeX macros from the shipped result files.

Numbers drifted between the abstract, the body and the appendix three times in this project --
NAR appeared as both 0.06 and 0.08, and a "38% unsupported" survived a change of CAR from 0.62 to
0.46. Copying values by hand is what caused that. This regenerates them, so a rerun updates the
paper and a contradiction becomes impossible rather than merely unlikely.

    python3 scripts/make_macros.py ../paper/xai4science > ../paper/xai4science/results.tex

The optional argument is a directory into which generated table bodies are written, so that a
table's rows are read from the result file too rather than typed beside it.
"""
import json, sys
from pathlib import Path

M = Path(__file__).resolve().parent.parent / "mechanism"


def load(n):
    p = M / n
    return json.loads(p.read_text()) if p.exists() else None


out = ["% GENERATED by scripts/make_macros.py -- do not edit by hand.",
       "% Every number below is read from a result file; rerun the script after any experiment.", ""]


def mac(name, val):
    out.append(f"\\newcommand{{\\{name}}}{{{val}}}")


ex = load("external_dysts.json")
if ex:
    n = len(ex)
    cl = sum(1 for r in ex if r["res"]["constant"]["closes"])
    mac("dystsN", n)
    mac("dystsConstCloses", cl)
    mac("dystsConstPct", f"{100*cl/n:.0f}\\%")
    mac("dystsConstPays", sum(1 for r in ex if r["res"]["constant"]["pays"]))
    mac("dystsSlowCloses", sum(1 for r in ex if r["res"]["slow"]["closes"]))
    mac("dystsMaxPay", f"{max(r['res']['constant']['r2'] for r in ex):+.3f}")

po = load("external_positives.json")
if po:
    mac("posSystems", po["n_systems"])
    mac("posRecallTrue", f"{po['recall_true']:.2f}")
    mac("posRecallEst", f"{po['recall_estimated']:.2f}")
    mac("posPrecision", f"{po['precision']:.2f}")
    mac("posClosureOnly", po["closure_only_accepts"])
    mac("posNegatives", po["n_negatives"])
    mac("posNARclosure", f"{po['closure_only_accepts']/po['n_negatives']:.2f}")
    _th = sorted({v for v in po["breakdown_theta"].values() if v is not None})
    if _th:
        mac("posThetaLo", f"{min(_th):.2f}")
        mac("posThetaHi", f"{max(_th):.2f}")

co = load("external_coordinates.json")
if co:
    import math
    fin = [r for r in co["rows"] if math.isfinite(r["origin"]) and math.isfinite(r["translated"])]
    mac("coordIdentical", len(fin))
    mac("coordTranslatedPct", f"{100*co['frac_translated']:.0f}\\%")

a = load("xai_cka.json")
if a and "configs" in a:
    import statistics as _st
    mac("XoneNARinsample", f"{a['nar_structural_insample_small']:.2f}")
    mac("XoneNARheldout", f"{a['nar_structural_heldout']:.2f}")
    mac("XoneNARboth", f"{a['nar_both']:.2f}")
    mac("XoneConfigs", len(a["configs"]))
    mac("XoneTriples", a["config"]["triples_per_config"])
    mac("XoneTriplesTotal", a["config"]["triples_per_config"] * len(a["configs"]))
    mac("XoneSeeds", a["config"]["seeds"])
    mac("XoneRealMedian",
        f"{_st.median(r['real']['causal_median'] for r in a['configs'].values()):.2f}")
    # worst separation over all nulls in all configurations: the number a sceptic should be given
    _au = [r[v]["auroc_vs_real"] for r in a["configs"].values()
           for v in r if v != "real" and r[v]["auroc_vs_real"] is not None]
    mac("XoneAUROCmin", f"{min(_au):.2f}")
    mac("XoneAUROCmedian", f"{_st.median(_au):.2f}")
    _cb = [(v, r[v]) for r in a["configs"].values() for v in r
           if r[v]["type"] == "correspondence-breaking"]
    mac("XoneCorrBreakG1", f"{sum(x['guard1'] for _, x in _cb)}")
    mac("XoneCorrBreakN", f"{len(_cb)}")

b = load("xai_sae.json")
if b:
    car = b.get("car_at_k", b.get("car_selected"))
    mac("XtwoFeatures", b["paired"])
    mac("XtwoCAR", f"{car:.2f}")
    mac("XtwoCARpct", f"{100*car:.0f}\\%")
    mac("XtwoUnsupportedPct", f"{100*(1-car):.0f}\\%")   # was hand-copied and went stale
    mac("XtwoControl", f"{b['car_control']:.2f}")
    mac("XtwoDelta", f"{b['delta_car']:+.2f}")
    mac("XtwoCIlo", f"{b['ci'][0]:.2f}")
    mac("XtwoCIhi", f"{b['ci'][1]:.2f}")
    mac("XtwoNAR", f"{b['nar']:.2f}")
    mac("XtwoDeltaCIlo", f"{b['delta_ci'][0]:+.2f}") if "delta_ci" in b else None
    mac("XtwoDeltaCIhi", f"{b['delta_ci'][1]:+.2f}") if "delta_ci" in b else None
    mac("XtwoArms", len(b["config"]["arms"]))
    if "positive_control_rate" in b:
        mac("XtwoPositiveControl", f"{b['positive_control_rate']:.2f}")
        if "positive_defined" in b:
            mac("XtwoPositiveDefined", b["positive_defined"])
            mac("XtwoPositiveUndefined", len(b["rows"]) - b["positive_defined"])
        if "positive_ci" in b:
            mac("XtwoPositiveCIlo", f"{b['positive_ci'][0]:.2f}")
            mac("XtwoPositiveCIhi", f"{b['positive_ci'][1]:.2f}")
        if "positive_wrong_sign" in b:
            mac("XtwoPositiveWrongSign", f"{b['positive_wrong_sign']:.2f}")
        # the arms where the control's own manipulation worked, and H's rate on those
        pa = b.get("per_arm", {})
        good = [v for v in pa.values() if v.get("positive_wrong_sign", 1.0) < 0.10]
        if good:
            mac("XtwoPositiveValidArms", len(good))
            mac("XtwoPositiveOnValid",
                f"{sum(v['positive'] for v in good)/len(good):.2f}")

# --- generated table bodies ------------------------------------------------------------------
# A hand-typed table drifts exactly as a hand-typed number does, and X2's arm table had drifted
# from its own pooled row. The rows are written from the result file instead.
if len(sys.argv) > 1 and b and "per_arm" in b:
    d = Path(sys.argv[1])

    def pretty(a):
        return a.replace("pythia", "Pythia").replace("-deduped", "").replace(" L", " L")

    lines = []
    for a, v in sorted(b["per_arm"].items()):
        lines.append(f"{pretty(a)} & {v['n']} & {v['car']:.2f} & {v['control']:.2f} & "
                     f"${v['car']-v['control']:+.2f}$ \\\\")
    lines.append("\\midrule")
    lines.append(f"pooled & \\textbf{{{b['paired']}}} & "
                 f"\\textbf{{{car:.2f}}} \\, {{\\footnotesize (CI ${b['ci'][0]:.2f}$--${b['ci'][1]:.2f}$)}} & "
                 f"\\textbf{{{b['car_control']:.2f}}} & "
                 f"$\\mathbf{{{b['delta_car']:+.2f}}}$")   # the row is closed by the caller
    (d / "x2_arms.tex").write_text(
        "% GENERATED by scripts/make_macros.py -- do not edit by hand.\n" + "\n".join(lines) + "\n")

    if "per_arm" in b and any("positive" in v for v in b["per_arm"].values()):
        pl = []
        for a, v in sorted(b["per_arm"].items()):
            if "positive" not in v:
                continue
            ws = v.get("positive_wrong_sign")
            pl.append(f"{pretty(a)} & {v.get('positive_defined', 0)} & {v['positive']:.2f} & "
                      + (f"{ws:.2f}" if ws is not None else "--") + " \\\\")
        (d / "x2_positive.tex").write_text(
            "% GENERATED by scripts/make_macros.py -- do not edit by hand.\n"
            + "\n".join(pl).rstrip("\\\\") + "\n")

print("\n".join(out))
