"""Emit LaTeX macros from the shipped result files.

Numbers drifted between the abstract, the body and the appendix three times in this project --
NAR appeared as both 0.06 and 0.08, and a "38% unsupported" survived a change of CAR from 0.62 to
0.46. Copying values by hand is what caused that. This regenerates them, so a rerun updates the
paper and a contradiction becomes impossible rather than merely unlikely.

    python3 scripts/make_macros.py ../paper/xai4science > ../paper/xai4science/results.tex

The optional argument is a directory into which generated table bodies are written, so that a
table's rows are read from the result file too rather than typed beside it.
"""
import json, sys
from pathlib import Path

M = Path(__file__).resolve().parent.parent / "mechanism"


def load(n):
    p = M / n
    return json.loads(p.read_text()) if p.exists() else None


out = ["% GENERATED by scripts/make_macros.py -- do not edit by hand.",
       "% Every number below is read from a result file; rerun the script after any experiment.", ""]


def mac(name, val):
    # TeX command names are letters only: a digit in the name silently truncates the command and
    # leaves the digit as typeset material, which in a preamble \input reads as
    # "Missing \begin{document}" -- an error that names neither the macro nor this file.
    assert name.isalpha(), f"macro name must be letters only, got {name!r}"
    out.append(f"\\newcommand{{\\{name}}}{{{val}}}")


LABEL = {"identity": "identity map (harness check)", "adjacent": "adjacent layer, same model",
         "real": "the correspondence under test", "permuted_pairs": "pairings permuted",
         "residue_shuffle": "residues permuted within protein",
         "orthogonal": "the same map, randomly rotated",
         "gaussian_matched": "covariance-matched Gaussian target",
         "donor_perm": "donor permuted at patch time", "untrained": "randomly initialised target",
         "mismatched": "fitted on disjoint text"}
SHORT = {"real": "real", "positive": "positive", "correspondence-breaking": "corr.-breaking",
         "randomised": "randomised", "degenerate": "degenerate",
         "task-confounded": "task-confounded", "consequence-test control": "test control"}


def cand_table(j, path):
    """One row per candidate, medians across configurations, written from the result file."""
    import statistics as _st
    cf = list(j["configs"].values())
    order = [v for v in ("identity", "adjacent", "real", "permuted_pairs", "residue_shuffle",
                         "orthogonal", "gaussian_matched", "mismatched", "untrained",
                         "donor_perm") if any(v in c for c in cf)]
    lines = []
    for v in order:
        rs = [c[v] for c in cf if v in c]
        med = lambda k: _st.median(r[k] for r in rs)
        au = [r["auroc_vs_real"] for r in rs if r.get("auroc_vs_real") is not None]
        g1 = sum(r["guard1"] for r in rs)
        acc = sum(r["accepted"] for r in rs)
        lines.append(
            f"{LABEL[v]} & {SHORT[rs[0]['type']]} & {med('r2'):.2f} & {med('cka'):.2f} & "
            f"{g1}/{len(rs)} & {med('causal_median'):+.2f} & "
            + (f"{_st.median(au):.3f}" if au and rs[0]["type"] != "positive" else "--")
            + f" & {acc}/{len(rs)}"
            + (r" \\" if v != order[-1] else ""))
    Path(path).write_text(
        "% GENERATED by scripts/make_macros.py -- do not edit by hand.\n" + "\n".join(lines) + "\n")


def corr_audit(j, prefix):
    """Macros shared by the two correspondence experiments (X1 language, X3 protein)."""
    import statistics as _st
    cf = j["configs"]
    mac(prefix + "Configs", len(cf))
    mac(prefix + "Triples", j["config"]["triples_per_config"])
    mac(prefix + "TriplesTotal", j["config"]["triples_per_config"] * len(cf))
    mac(prefix + "NARstructural", f"{j['nar_structural_heldout']:.2f}")
    mac(prefix + "NARboth", f"{j['nar_both']:.2f}")
    mac(prefix + "NARinsample", f"{j['nar_structural_insample_small']:.2f}")
    if "par_both" in j:
        mac(prefix + "PAR", f"{j['par_both']:.2f}")
    au = [r[v]["auroc_vs_real"] for r in cf.values() for v in r
          if v != "real" and r[v].get("auroc_vs_real") is not None
          and r[v]["type"] not in ("positive",)]
    if au:
        mac(prefix + "AUROCmin", f"{min(au):.2f}")
        mac(prefix + "AUROCmedian", f"{_st.median(au):.2f}")
    mac(prefix + "RealMedian",
        f"{_st.median(r['real']['causal_median'] for r in cf.values()):.2f}")
    mac(prefix + "RealAccepted", sum(r["real"]["accepted"] for r in cf.values()))
    # How many candidates carry the SAME CKA as the genuine correspondence, to three decimals?
    # CKA never looks at the claimed map, so a correspondence and its rotation score identically.
    same, tot = [], 0
    for r in cf.values():
        base = round(r["real"]["cka"], 3)
        n = sum(1 for v in r if v != "real" and r[v]["type"] not in ("positive", "degenerate")
                and round(r[v]["cka"], 3) == base)
        same.append(n); tot = max(tot, sum(1 for v in r if v != "real"
                                           and r[v]["type"] not in ("positive", "degenerate")))
    mac(prefix + "CKAsame", min(same))
    mac(prefix + "CKAsameOf", tot)
    mac(prefix + "CKAreal", f"{_st.median(r['real']['cka'] for r in cf.values()):.3f}")
    if len(sys.argv) > 1:
        cand_table(j, Path(sys.argv[1]) / f"{prefix.lower()}_cands.tex")


ex = load("external_dysts.json")
if ex:
    n = len(ex)
    cl = sum(1 for r in ex if r["res"]["constant"]["closes"])
    mac("dystsN", n)
    mac("dystsConstCloses", cl)
    mac("dystsConstPct", f"{100*cl/n:.0f}\\%")
    mac("dystsConstPays", sum(1 for r in ex if r["res"]["constant"]["pays"]))
    mac("dystsSlowCloses", sum(1 for r in ex if r["res"]["slow"]["closes"]))
    mac("dystsMaxPay", f"{max(r['res']['constant']['r2'] for r in ex):+.3f}")

po = load("external_positives.json")
if po:
    mac("posSystems", po["n_systems"])
    mac("posRecallTrue", f"{po['recall_true']:.2f}")
    mac("posRecallEst", f"{po['recall_estimated']:.2f}")
    mac("posPrecision", f"{po['precision']:.2f}")
    mac("posClosureOnly", po["closure_only_accepts"])
    mac("posNegatives", po["n_negatives"])
    mac("posNARclosure", f"{po['closure_only_accepts']/po['n_negatives']:.2f}")
    _th = sorted({v for v in po["breakdown_theta"].values() if v is not None})
    if _th:
        mac("posThetaLo", f"{min(_th):.2f}")
        mac("posThetaHi", f"{max(_th):.2f}")

co = load("external_coordinates.json")
if co:
    import math
    fin = [r for r in co["rows"] if math.isfinite(r["origin"]) and math.isfinite(r["translated"])]
    mac("coordIdentical", len(fin))
    mac("coordTranslatedPct", f"{100*co['frac_translated']:.0f}\\%")

fam = load("xai_families.json")
if fam:
    _rows = [r for v in fam["pairs"].values() for r in v["rows"]]
    mac("FamDraws", len(_rows))
    mac("FamPerFamily", fam["n_draw_per_family"])
    mac("FamFamilies", len(fam["config"]["families"]))
    mac("FamPairs", len(fam["pairs"]))
    mac("FamInterventions", fam["config"]["interventions_per_draw"])
    mac("FamNARone", f"{sum(r['guard1'] for r in _rows)/len(_rows):.2f}")
    mac("FamNARboth", f"{sum(r['accepted'] for r in _rows)/len(_rows):.2f}")
    mac("FamWorstCausal", f"{max(r['causal_median'] for r in _rows):.2f}")
    mac("FamAnyNullPass", max(v["any_null_pass"] for v in fam["pairs"].values()))

e = load("xai_esm.json")
if e and "configs" in e:
    corr_audit(e, "Xthree")
    mac("XthreeProteins", e["config"]["n_prot"])
    mac("XthreeResidues", e["config"]["seq_len"])

a = load("xai_cka.json")
if a and "configs" in a:
    corr_audit(a, "Xone")
    mac("XoneSeeds", a["config"]["seeds"])
    _cb = [(v, r[v]) for r in a["configs"].values() for v in r
           if r[v]["type"] == "correspondence-breaking"]
    mac("XoneCorrBreakGone", f"{sum(x['guard1'] for _, x in _cb)}")
    mac("XoneCorrBreakN", f"{len(_cb)}")

b = load("xai_sae.json")
if b:
    car = b.get("car_at_k", b.get("car_selected"))
    mac("XtwoFeatures", b["paired"])
    mac("XtwoCAR", f"{car:.2f}")
    mac("XtwoCARpct", f"{100*car:.0f}\\%")
    mac("XtwoUnsupportedPct", f"{100*(1-car):.0f}\\%")   # was hand-copied and went stale
    mac("XtwoControl", f"{b['car_control']:.2f}")
    mac("XtwoDelta", f"{b['delta_car']:+.2f}")
    mac("XtwoCIlo", f"{b['ci'][0]:.2f}")
    mac("XtwoCIhi", f"{b['ci'][1]:.2f}")
    mac("XtwoNAR", f"{b['nar']:.2f}")
    mac("XtwoDeltaCIlo", f"{b['delta_ci'][0]:+.2f}") if "delta_ci" in b else None
    mac("XtwoDeltaCIhi", f"{b['delta_ci'][1]:+.2f}") if "delta_ci" in b else None
    mac("XtwoArms", len(b["config"]["arms"]))
    mac("XtwoUntestable", b["untestable"])
    mac("XtwoSelected", len(b["rows"]))
    if "car_activate" in b:
        mac("XtwoCARactivate", f"{b['car_activate']:.2f}")
        mac("XtwoAgree", f"{b['agree_given_ablation']:.2f}")
        mac("XtwoAgreeN", int(round(b["agree_given_ablation"]
                                    * sum(r["supported"] for r in b["rows"] if r["controls"]
                                          and len(r["per_seq"]) >= 12))))
        mac("XtwoAblationN", sum(r["supported"] for r in b["rows"]
                                 if r["controls"] and len(r["per_seq"]) >= 12))
    if "positive_control_rate" in b:
        mac("XtwoPositiveControl", f"{b['positive_control_rate']:.2f}")
        if "positive_defined" in b:
            mac("XtwoPositiveDefined", b["positive_defined"])
            mac("XtwoPositiveUndefined", len(b["rows"]) - b["positive_defined"])
        if "positive_ci" in b:
            mac("XtwoPositiveCIlo", f"{b['positive_ci'][0]:.2f}")
            mac("XtwoPositiveCIhi", f"{b['positive_ci'][1]:.2f}")
        if "positive_wrong_sign" in b:
            mac("XtwoPositiveWrongSign", f"{b['positive_wrong_sign']:.2f}")
        # the arms where the control's own manipulation worked, and H's rate on those
        pa = b.get("per_arm", {})
        good = [v for v in pa.values() if v.get("positive_wrong_sign", 1.0) < 0.10]
        if good:
            mac("XtwoPositiveValidArms", len(good))
            mac("XtwoPositiveOnValid",
                f"{sum(v['positive'] for v in good)/len(good):.2f}")

# --- generated table bodies ------------------------------------------------------------------
# A hand-typed table drifts exactly as a hand-typed number does, and X2's arm table had drifted
# from its own pooled row. The rows are written from the result file instead.
if len(sys.argv) > 1 and b and "per_arm" in b:
    d = Path(sys.argv[1])

    def pretty(a):
        return a.replace("pythia", "Pythia").replace("-deduped", "").replace(" L", " L")

    lines = []
    for a, v in sorted(b["per_arm"].items()):
        lines.append(f"{pretty(a)} & {v['n']} & {v['car']:.2f} & {v['control']:.2f} & "
                     f"${v['car']-v['control']:+.2f}$ \\\\")
    lines.append("\\midrule")
    lines.append(f"pooled & \\textbf{{{b['paired']}}} & "
                 f"\\textbf{{{car:.2f}}} \\, {{\\footnotesize (CI ${b['ci'][0]:.2f}$--${b['ci'][1]:.2f}$)}} & "
                 f"\\textbf{{{b['car_control']:.2f}}} & "
                 f"$\\mathbf{{{b['delta_car']:+.2f}}}$")   # the row is closed by the caller
    (d / "x2_arms.tex").write_text(
        "% GENERATED by scripts/make_macros.py -- do not edit by hand.\n" + "\n".join(lines) + "\n")

    if "per_arm" in b and any("positive" in v for v in b["per_arm"].values()):
        pl = []
        for a, v in sorted(b["per_arm"].items()):
            if "positive" not in v:
                continue
            ws = v.get("positive_wrong_sign")
            pl.append(f"{pretty(a)} & {v.get('positive_defined', 0)} & {v['positive']:.2f} & "
                      + (f"{ws:.2f}" if ws is not None else "--") + " \\\\")
        (d / "x2_positive.tex").write_text(
            "% GENERATED by scripts/make_macros.py -- do not edit by hand.\n"
            + "\n".join(pl).rstrip("\\\\") + "\n")

_defined = [l.split("{\\")[1].split("}")[0] for l in out if l.startswith("\\newcommand")]
_dupes = sorted({n for n in _defined if _defined.count(n) > 1})
assert not _dupes, f"macro defined more than once, which LaTeX rejects: {_dupes}"

print("\n".join(out))
